using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EcommAppDAL.Models
{/// <summary>
/// This is Categories EF Core for Categories Table.
/// </summary>
    [Table("Category")] //category table
    public class Categories
    {
        [Key]
        [Column("ID")] //autogenerated
        public int CategoryId { get; set; } //refereed in product tale
        [Required]
        [DataType("varchar")]
        [Column("Name")]
        [MaxLength(100, ErrorMessage = "Name cannot me more than 100 characters. Consider adding shortform")]
        public string CategoryName { get; set; }
        [DataType("date")]
        [Column("Date of Creation")]
        public  string? CategoryDate { get; set; }
    }
}
