using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EcommAppDAL.Models
{/// <summary>
/// This is ProductSpecification EF Core for Product and Specification mapping table.
/// </summary>
    [Table("Product Specification")]
  
    public class ProductSpecifications
    {
        [Key]
        [Column("ID")]
        public int ProductSpecificationId { get; set; } //autogenerated
        [ForeignKey("Specifications")]
        public int? SpecificationId { get; set; } //adding foreign key from Specification table //make sure it's non nullable
        public virtual Specifications? Specifications { get; set; }
        [ForeignKey("Product")]
        public int? ProductId { get; set; } //adding foreign key from product table //make sure it's non nullable
        public virtual Product? Product { get; set; }

    }
}
