using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EcommAppDAL.Models
{/// <summary>
/// This is Specifications EF Core for Specifications Table.
/// </summary>
    [Table("Specifications")]
    public class Specifications
    {
        [Key]
        [Column("ID")]
        public int SpecificationId { get; set; } //autogenerated
        [Required]
        [DataType("varchar")]
        [Column("Name")]
        [MaxLength(100, ErrorMessage = "Specification Name cannot me more than 100 characters. Consider adding short names")]
        public string SpecificationName { get; set; }
        [DataType("varchar")]
        [Column("Details")]
        [MaxLength(100, ErrorMessage = "Specification Type cannot me more than 100 characters. Consider adding short names")]
        public string? SpecificationDetail { get; set; }
    }
}
