using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EcommAppDAL.Models
{
    [Table("Comments")]
    public class Comment
    {
        [Key]
        [Column("Id")] //autogenerated
        public int CommentId { get; set; }
        [ForeignKey("User")]
        public int? UserId { get; set; } //adding foreign key from user table //make sure it's non nullable
        public virtual User? User { get; set; }
        [ForeignKey("Product")]
        public int? ProductId { get; set; } //adding foreign key from product table //make sure it's non nullable
        public virtual Product? Product { get; set; }
        [Required]
        [DataType("varchar(MAX)")]
        [Column("Comment")]
        public string CommentDetails { get; set; }
        [DataType("date")]
        [Column("Date of Comment")]
        public string? CommentDate { get; set; }
        [DataType("int")]
        [Column("ParentCommentId")]
        public int? ParentCommentId { get; set; }
        //public List<Comment> Children { get; set; }
        //[ForeignKey("Comment")]
        //public int? ParentCommentId { get; set; } //adding foreign key from state table //make sure it's non nullable
        //public virtual Comment? Comments { get; set; }
    }
}
