using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EcommAppBLL.ModelViews
{/// <summary>
/// This is ProductView that has all the columns for Product View
/// </summary>
    public class ProductView
    {
        
        public int ProductId { get; set; } //autogenerated
        public string ProductName { get; set; }
        public string? ProductDescription { get; set; }
        public float ProductPrice { get; set; }
        public int ProductCount { get; set; }
        
        public int? CategoryId { get; set; } //adding foreign key from category table //make sure it's non nullable
        
    }
}
