using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EcommAppDAL.Models
{/// <summary>
/// This is Carts EF Core for Cart Table.
/// </summary>
    [Table("Cart")]
    public class Cart
    {
        [Key]
        [Column("ID")]
        public int CartId { get; set; } //autogenerated
        
        [ForeignKey("User")]
        public int? UserId { get; set; } //adding foreign key from User table //make sure it's non nullable
        public virtual User? User { get; set; }
        [Required]
        [DataType("float")]
        [Column("Price")]
        public float CartPrice { get; set; }

    }
}
