using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EcommAppDAL.Models
{/// <summary>
/// This is CartProducts EF Core for Cart and Products mapping table.
/// </summary>
    [Table("Cart Products")]
    public class CartProducts
    {
        [Key]
        [Column("ID")]
        public int CartProductId { get; set; } //autogenerated
        [ForeignKey("Cart")]
        public int? CartId { get; set; } //adding foreign key from cart table //make sure it's non nullable
        public virtual Cart? Cart { get; set; }
        [ForeignKey("Product")]
        public int ProductId { get; set; } //adding foreign key from product table //make sure it's non nullable
        public virtual Product? Product { get; set; }
        [Required]
        [DataType("int")]
        [Column("Count")]
        public int CartCount { get; set; }
        //[Required]
        //[DataType("float")]
        //[Column("Price")]
        //public float CartPrice { get; set; }


    }
}
