//using System;
//using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;

//namespace EcommAppDAL.Models.Shopping
//{
//        [Table("Order Checkout")]
//        public class OrderCheckout
//        {
//            [Key]
//            [Column("ID")]
//            public int OrderCheckoutId { get; set; } //autogenerated
//            [ForeignKey("Cart")]
//            public int? CartId { get; set; } //adding foreign key from cart table //make sure it's non nullable
//            public virtual Cart? Cart { get; set; }
//            [ForeignKey("Order")]
//            public int? OrderId { get; set; } //adding foreign key from order table //make sure it's non nullable
//            public virtual Order? Order { get; set; }
//            [Required]

//           // [DataType("int")]
//           // [Column("Count")]
//           // public int CartCount { get; set; }
//            //[Required]
//            //[DataType("float")]
//            //[Column("Price")]
//            //public float CartPrice { get; set; }


//        }
    
//}
