using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EcommAppDAL.Models
{/// <summary>
/// This is Order EF Core for Orders Table.
/// </summary>
    [Table("Order")]
    public class Order
    {
        [Key]
        [Column("ID")]
        public int OrderId { get; set; } //autogenerated
        [DataType("date")]
        [Column("OrderDate")]
        public DateTime OrderDate { get; set; }
        [ForeignKey("Cart")]
        public int? CartId { get; set; } //adding foreign key from carttable //make sure it's non nullable
        public virtual Cart? Cart { get; set; }
        //[ForeignKey("CartProducts")]
        // public int? CartProductId { get; set; } //adding foreign key from CartProductId table //make sure it's non nullable
        //  public virtual CartProducts? CartProducts { get; set; }

        [ForeignKey("Address")]
        public int? AddressId { get; set; }
        public virtual Address? Address { get; set; }
        
        
        [ForeignKey("User")]
        public int? UserId { get; set; }
        public virtual User? User { get; set; }
       // [ForeignKey("Cart")]
        public float OrderPrice { get; set; }
        

    }
}
